import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Primary brand colors
        primary: "#0021c7",
        "primary-container": "#0f33ff",
        "on-primary": "#ffffff",
        "on-primary-container": "#c6cbff",
        "primary-fixed": "#dfe0ff",
        "primary-fixed-dim": "#bcc2ff",
        "on-primary-fixed": "#000b62",
        "on-primary-fixed-variant": "#0025d8",
        // Surface colors
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f3f3f4",
        "surface-container": "#eeeeee",
        "surface-container-high": "#e8e8e8",
        "surface-container-highest": "#e2e2e2",
        "surface-alt": "#F8FAFC",
        "surface-bright": "#f9f9f9",
        "surface-dim": "#dadada",
        "surface-variant": "#e2e2e2",
        surface: "#f9f9f9",
        // Text colors
        "text-main": "#1E293B",
        "text-muted": "#64748B",
        "on-surface": "#1a1c1c",
        "on-surface-variant": "#444557",
        "on-background": "#1a1c1c",
        // Border colors
        "border-subtle": "#E2E8F0",
        "border-strong": "#CBD5E1",
        "outline": "#757689",
        "outline-variant": "#c5c5da",
        // Secondary colors
        secondary: "#565e74",
        "secondary-container": "#dae2fd",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#5c647a",
        "secondary-fixed": "#dae2fd",
        "secondary-fixed-dim": "#bec6e0",
        "on-secondary-fixed": "#131b2e",
        "on-secondary-fixed-variant": "#3f465c",
        // Tertiary colors
        tertiary: "#821100",
        "tertiary-container": "#ad1a00",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#ffbfb2",
        "tertiary-fixed": "#ffdad3",
        "tertiary-fixed-dim": "#ffb4a5",
        "on-tertiary-fixed": "#3e0400",
        "on-tertiary-fixed-variant": "#8e1400",
        // Error colors
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        // Inverse
        "inverse-surface": "#2f3131",
        "inverse-on-surface": "#f0f1f1",
        "inverse-primary": "#bcc2ff",
        background: "#f9f9f9",
        "surface-tint": "#2440ff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        sm: "0.125rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        "margin-desktop": "2.5rem",
        "margin-mobile": "1rem",
        xs: "0.25rem",
        sm: "0.5rem",
        md: "1rem",
        lg: "1.5rem",
        xl: "2.5rem",
        "2xl": "4rem",
        gutter: "1.5rem",
      },
      fontFamily: {
        sans: ["Hanken Grotesk", "sans-serif"],
        "label-md": ["Hanken Grotesk"],
        "label-sm": ["Hanken Grotesk"],
        "headline-md": ["Hanken Grotesk"],
        "body-lg": ["Hanken Grotesk"],
        "body-sm": ["Hanken Grotesk"],
        "display-lg": ["Hanken Grotesk"],
        "headline-sm": ["Hanken Grotesk"],
        "display-lg-mobile": ["Hanken Grotesk"],
        "body-md": ["Hanken Grotesk"],
      },
      fontSize: {
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-md": ["30px", { lineHeight: "38px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-sm": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "display-lg-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};

export default config;
